

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - OPENAI_API_KEY=${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}

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tax_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: